# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

bioc_required: yes
use_bioc: yes
r_check_args: --as-cran

r:
  - release
  
# tlmgr line added on 7 Jun 2016 as workaround for:
# https://github.com/travis-ci/travis-ci/issues/7863
before_install:
  - tlmgr install xkeyval
  - sudo apt-get install tk -y
  - sudo apt-get install tk-dev -y
  - sudo apt-get install tcl -y
  - sudo apt-get install tcl-dev -y

# the following didn't seem to fix the neurocondutor test fails
#addons:
#  apt:
#    packages:
#    - tk 
#    - tk-dev
#    - tcl 
#    - tcl-dev

